[tool.poetry]
name = "poetry-stabs-package-sample"
version = "0.1.0"
description = ""
authors = ["0num4 <r.oonuma@matsuri-tech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
