name: release-testpypi
on:
  # release:
  #   types: [published]
  push:
    branches:
      - main
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup@main
      - name: print poetry version
        run: poetry --version
      - name: poetry version patch
        run: poetry version patch
      - name: git tag
        run: git tag -a "v$(poetry version | awk '{print $2}')" -m "v$(poetry version | awk '{print $2}')"
      - name: git push
        run: git push origin "v$(poetry version | awk '{print $2}')"
      - name: build
        run: poetry build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: ./dist/
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     python -m twine upload --repository testpypi dist/*
  pypi-publish:
    name: Publish to testpypi
    runs-on: ubuntu-latest
    env:
      name: pypi
      url: https://test.pypi.org/project/poetry-stabs-package-sample/
    needs: release
    permissions:
      id-token: write
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: ./dist/
      - name: publish-testpypi
        id: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        continue-on-error: true
      - name: retry publish testpypi
        if: steps.publish.outcome == 'failure'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        continue-on-error: true
      - name: retry publish testpypi (2nd attempt)
        if: steps.publish.outcome == 'failure'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        continue-on-error: true
