name: release-testpypi
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: print python version
        run: python --version
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: ./dist/
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     python -m twine upload --repository testpypi dist/*
  pypi-publish:
    name: Publish to testpypi
    runs-on: ubuntu-latest
    env:
      name: pypi
      url: https://test.pypi.org/project/poetry-stabs-package-sample/
    needs: release
    permissions:
      id-token: write
    steps:
      - name: Retrive release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: ./dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'
      - name: publish testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
