name: release-testpypi
on:
  push:
    branches:
      - master
      - release
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: print python version
        run: python --version
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: ./dist/
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     python -m twine upload --repository testpypi dist/*
  pypi-publish:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrive release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist
      - name: publish testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
